# Default values for rh-odf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cluster_name:
aap:
  name: ansible-automation-platform-operator
  namespace: ansible-automation-platform
  installPlanApproval: Manual
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel:
  create_preload_data: false
  route_tls_termination_mechanism: Edge
  garbage_collect_secrets: false
  ingress_type: Route
  loadbalancer_port: 80
  projects_use_existing_claim: _Yes_
  image_pull_policy: IfNotPresent
  projects_storage_size: 8Gi
  task_privileged: false
  projects_storage_access_mode: ReadWriteMany
  projects_persistence: false
  replicas: 1
  admin_user: admin
  loadbalancer_protocol: http
  nodeport_port: 30080