{{ if .Values.odf.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.odf.operatorGroup }}
  namespace: {{ .Values.odf.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
  - {{ .Values.odf.namespace }}
{{ end }}