{{ if .Values.odf.enabled }}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.odf.namespace }}
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "1"
  labels:
    openshift.io/cluster-monitoring: "true"
{{ end }}