{{ if .Values.odf_enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: update-loadbalancer
  annotations:
    argocd.argoproj.io/hook: PostSync
  namespace: "openshift-gitops"
spec:
  template:
    spec:
      restartPolicy: "OnFailure"
      containers:
      - name: update-loadbalancer
        image: registry.redhat.io/openshift4/ose-cli:v4.9.0
        command:
            - "/bin/bash"
            - "-c"
            - >- 
              echo "Annotating nooba-mgmt service Loadbalancer type" &&
              oc annotate service noobaa-mgmt -n openshift-storage service.beta.kubernetes.io/aws-load-balancer-type=nlb --overwrite=true &&
              echo "Annotating s3 service Loadbalancer type" &&
              oc annotate service s3 -n openshift-storage service.beta.kubernetes.io/aws-load-balancer-type=nlb --overwrite=true &&
              echo "Patch nooba-mgmt Source Range" &&
              oc patch service noobaa-mgmt -n openshift-storage -p '{"spec":{"loadBalancerSourceRanges":["{{ .Values.vpc_cidr }}","{{ .Values.vpn_cidr }}"]}}' &&
              echo "Patch s3 Source Range" &&
              oc patch service s3 -n openshift-storage -p '{"spec":{"loadBalancerSourceRanges":["{{ .Values.vpc_cidr }}","{{ .Values.vpn_cidr }}"]}}' &&
              echo "Annotating ocs-storagecluster-ceph-rbd to set as default" &&
              oc annotate storageclass ocs-storagecluster-ceph-rbd storageclass.kubernetes.io/is-default-class='true' &&
              oc annotate storageclass gp2 storageclass.kubernetes.io/is-default-class-
      serviceAccountName: openshift-gitops-argocd-application-controller
{{ end }}
