---
setup_dependencies: true
create_cluster: true
install_argo_apps: true
platform: aws

vpc_id:
cluster_name: cluster
openshift_version: 4.9.43
region: us-east-1
availability_zones:
  - "{{ region }}a"
  - "{{ region }}b"
  - "{{ region }}c"
base_domain: cmscloud.local
home_dir: "{{ lookup('env', 'HOME') }}"
install_dir: "{{ lookup('env', 'HOME') }}/{{ cluster_name }}-openshift-install"

openshift:
  release: "{{ lookup('vars', 'openshift_version') | default('latest', true) }}"
  release_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp"

credentials_mode: Passthrough

worker:
  ec2_type: m5.4xlarge
  rootvolume:
    iops: 2000
    size: 120
    type: io1
  replicas: 3

master:
  ec2_type: m5.2xlarge
  rootvolume:
    iops: 2000
    size: 120
    type: io1
  replicas: 3

infra:
  ec2_type: m5.4xlarge

# Storage class used for monitoring (alert manager and prometheus)
monitoring_storage_class: gp2

# Number of days to retain monitoring data
prometheus_retention: 15d

# PV size for prometheus metrics
prometheus_storage: 40Gi

# PV size for alertmanager
alertmanager_storage: 40Gi

# Image version should argo-containers/argocd-repo-server-sops/Dockerfile
argocd_image_version: 'v1.4.4'

# Security Group Variables
cloudbees_cidr: 10.223.128.0/22
vpn_cidr: 10.232.32.0/19

console_cert: "{{ lookup('env', 'CONSOLE_CERT') }}"
console_cert_key: "{{ lookup('env', 'CONSOLE_CERT_KEY') }}"

# machineautoscaler vars
machineset_types:
  infra:
    replicas:
      min: 1
      max: 2
  worker:
    replicas:
      min: 1
      max: 2
  storage:
    replicas:
      min: 1
      max: 2

loop_count: 0
app_set_ready: False

# Gitops Values
gitops_version: 1.7
gitops_helm_secrets_version: 3.15.0
gitops_vals_version: 0.18.0
gitops_sops_version: 3.7.3
gitops_helm_version: 3.10.3
gitops_namespace: "openshift-gitops"

redhat_operators_catalog: redhat/redhat-operator-index:v4.12
redhat_operators:
  # Day 1 Apps
  odf:
    name: odf-operator
    namespace: openshift-storage
    source: redhat-operator-index
    sourceNamespace: openshift-marketplace
    installPlanApproval: Automatic
    operatorGroup: openshift-storage-operatorgroup
    channel: stable-4.12
    ose_cli_image: registry.redhat.io/openshift4/ose-cli:v4.12.0

  # Day 2 Apps
  gitops:
    name: openshift-gitops-operator
    channel: gitops-{{ gitops_version }}
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace

# Fluent Bit logging Variables
splunk_hec_token:
splunk_channel_id:
cloud_account:
fluent_bit:
  namespace: fluent-bit-logging
  cm_name: fluent-bit
  secret_name: fluent-bit-secrets
  splunk_hec_url: hec.splunk.backends.cms.gov
  image:
    repository: registry.connect.redhat.com/calyptia/fluent-bit
    tag: 1.9.6
    pullPolicy: IfNotPresent
  rbac:
    nodeAccess: true
  podSecurityPolicy:
    create: true
  openShift:
    enabled: true
    securityContextConstraints:
      create: true
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    privileged: true
