# Default values for ldap-groupsnc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


gso:
  #ldap_groupsync vars
  group_membership_attr: uniquemember
  group_name_attr: cn
  basedn:
  user_name_attr: uid
  user_uid_attr: dn
  sync_schedule: 0,10,20,30,40,50 * * * *
  # sub
  name: group-sync-operator
  namespace: group-sync-operator
  installPlanApproval: Manual
  source: community-operators
  sourceNamespace: openshift-marketplace

  # ldap values passed in
  group_filter:
  cluster_admin_group:
  cluster_view_group:
  radiant_url: 