{{ if .Values.custom_console }}
apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  componentRoutes:
    - name: console
      namespace: openshift-console
      hostname: openshift.{{ .Values.cluster_name }}.{{ .Values.base_domain }}
      servingCertKeyPairSecret:
        name: console-tls
  domain: apps.{{ .Values.cluster_name }}.{{ .Values.base_domain }}
{{ end }}