#!/usr/local/bin/ansible-playbook
---
- name: Run Role
  hosts: localhost
  gather_facts: no
  environment:
    K8S_AUTH_SSL_CA_CERT: '/etc/pki/tls/certs/ca-bundle.crt'
    K8S_AUTH_VERIFY_SSL: 'no'
    AWS_REGION: "{{ region }}"
  vars:
    setup_dependencies: false
    create_cluster: false
    create_cluster_acm: true
    install_argo: true
    install_argo_apps: true
    test_argo_apps: false
    remove_kubeadmin: false
    restore: false
  vars_files:
    - vars/all/main.yml
    - vars/all/operators.yml
    - "vars/{{ env }}/main.yml"
  roles: 
    - iac-ansible
