#!/usr/local/bin/ansible-playbook
---
- name: Create OpenShift Cluster
  hosts: localhost
  gather_facts: no 
  environment:
    K8S_AUTH_SSL_CA_CERT: '/etc/pki/tls/certs/ca-bundle.crt'
    K8S_AUTH_VERIFY_SSL: 'no'
  vars_files:
    - vars/all/main.yml
  tasks:
  - name: Check if env is defined
    set_fact: 
      env: "{{ lookup('env', 'env') }}"

  - name: Confirm Cluster
    pause:
      prompt: "Confirm cluster (infra/dev/test/sbx/mgmt/prod/impl)"
    register: cluster_response
    delegate_to: localhost
    when: env == ""

  - name: Store Env
    set_fact:
      env: "{{ cluster_response.user_input }}"
    when: env == ""

  - name: "Include vars for {{ env }}"
    include_vars: "vars/{{ env }}/main.yml"

- name: Run Role
  hosts: localhost
  gather_facts: no
  environment:
    K8S_AUTH_SSL_CA_CERT: '/etc/pki/tls/certs/ca-bundle.crt'
    K8S_AUTH_VERIFY_SSL: 'no'
    AWS_REGION: "{{ region }}"
  vars:
    setup_dependencies: true
    create_cluster: true
    create_cluster_acm: false
    install_argo: true
    restore: false
    install_argo_apps: true
    test_argo_apps: true
    remove_kubeadmin: false
  vars_files:
    - vars/all/main.yml
    - "vars/{{ hostvars['localhost']['env'] }}/main.yml"
  roles: 
    - iac-ansible
