#!/usr/local/bin/ansible-playbook
---
- name: Destroy Cluster
  hosts: localhost
  gather_facts: no
  environment:
    K8S_AUTH_SSL_CA_CERT: '/etc/pki/tls/certs/ca-bundle.crt'
    K8S_AUTH_VERIFY_SSL: 'no'
    AWS_REGION: "{{ region }}"
  vars:
    destroy_cluster: false
    destroy_cluster_acm: true
  vars_files:
    - vars/all/main.yml
    - "vars/{{ env }}/main.yml"
  roles: 
    - destroy-cluster
