#!/usr/local/bin/ansible-playbook
---
- name: Run Role
  hosts: localhost
  gather_facts: false
  environment:
    K8S_AUTH_SSL_CA_CERT: '/etc/pki/tls/certs/ca-bundle.crt'
    K8S_AUTH_VERIFY_SSL: 'no'
    AWS_REGION: "{{ region }}"
  vars_files:
    - vars/all/main.yml
    - "vars/{{ env }}/main.yml"
  roles:
    - mirror-operators
