apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
    - names: 
      - api.{{ .Values.cluster_name }}.{{ .Values.base_domain }}
      servingCertificate:
        name: api-cert-secret