{{ if .Values.custome_certs_enabled }}
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  encryption:
    type: aescbc
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
    - names: 
      - api.{{ .Values.cluster_name }}.{{ .Values.base_domain }}
      servingCertificate:
        name: api-cert-secret
{{ end }}