kind: IngressController
apiVersion: operator.openshift.io/v1
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-options: Replace=false
    argocd.argoproj.io/sync-options: Prune=false
spec:
{{ if .Values.custom_certs_enabled }}
  defaultCertificate:
    name: ingress-cert-secret
{{ end }}
  endpointPublishingStrategy:
    loadBalancer:
{{ if semverCompare "~4.12.0" .Values.openshift_version }}
      allowedSourceRanges:
      - "0.0.0.0/0"
{{ end }}
      dnsManagementPolicy: Managed
      providerParameters:
        aws:
          type: NLB
        type: AWS
      scope: Internal
    type: LoadBalancerService
{{ if .Values.enable_external_load_balancer }}
  routeSelector:
    matchExpressions:
      - key: momot.router
        operator: NotIn
        values:
          - external
{{ end }}
  domain: apps.{{ .Values.cluster_name }}.{{ .Values.base_domain }}
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      key: infra
      value: reserved
    - effect: NoExecute
      key: infra
      value: reserved