# Default values for compliance operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
compliance:
  name: compliance-operator
  namespace: openshift-compliance
  installPlanApproval: Manual
  source: redhat-operators
  sourceNamespace: openshift-marketplace  
  nameSub: compliance-operator-sub
  channel: 