apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: jaeger-product-group
  namespace: {{ .Values.jeager.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
