apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: elasticsearch-operator-group
  namespace: {{ .Values.elasticSearch.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
