apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.elasticSearch.name }}
  namespace: {{ .Values.elasticSearch.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: {{ .Values.elasticSearch.channel }}
  installPlanApproval: {{ .Values.elasticSearch.installPlanApproval }}
  name: {{ .Values.elasticSearch.name }}
  source: {{ .Values.elasticSearch.source }}
  sourceNamespace: {{ .Values.elasticSearch.sourceNamespace }}