apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.serviceMesh.controlPlane.namespace }}
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    openshift.io/cluster-monitoring: "true"