{{ if .Values.compliance.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.compliance.name }}
  namespace: {{ .Values.compliance.namespace }}
spec:
  targetNamespaces:
  - {{ .Values.compliance.namespace }}
{{ end }}
