apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    release.openshift.io/create-only: 'true'
  name: cluster
spec: 
  allowedRegistriesForImport:
    - domainName: quay.io
      insecure: false
    - domainName: registry.redhat.io
      insecure: false
    - domainName: artifactory.cloud.cms.gov
      insecure: false
  registrySources:
    allowedRegistries:
      - quay.io
      - registry.redhat.io
      - artifactory.cloud.cms.gov