{{ if .Values.acs.enabled }}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.acs.namespace }}
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
{{ end }}