{{ if .Values.acs.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs-operator
  namespace: {{ .Values.acs.namespace }}
  annotations:
    olm.providedAPIs: >-
      Central.v1alpha1.platform.stackrox.io,SecuredCluster.v1alpha1.platform.stackrox.io
{{ end }}