---
- name: Set artifactory auth
  ansible.builtin.set_fact:
    docker_artifactory_auth: "{{ svc_acct_name }}:{{ svc_acct_password }}"

- name: Create OpenShift Custom Web Console URL Certificate Secret
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    force: yes
    definition: "{{ lookup('template','secrets/' + 'web-console-cert-secret.yml.j2') }}"
  no_log: true
  when: custom_certs_enabled

- name: Get Ingress Facts
  k8s_info:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    kind: Service
    name: router-default
    namespace: openshift-ingress
  register: ingress_facts

- name: Create Group Sync Operator Namespace 
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    definition: 
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        annotations:
          openshift.io/node-selector: ''
        labels:
          app.kubernetes.io/instance: ldap-groupsync
          openshift.io/cluster-monitoring: 'true'
        name: group-sync-operator
  when: oauth.groupsync_enabled

- name: Create Secret for Groupsync 
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    force: yes
    definition: "{{ item }}"
  loop:
    - "{{ lookup('template','secrets/' + 'gso-creds.yml.j2') }}"
    - "{{ lookup('template','secrets/' + 'gso-ca.yml.j2') }}"
  no_log: true
  when: oauth.groupsync_enabled
  
- name: Create Secret for LDAP
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    definition: "{{ item }}"
  loop:
    - "{{ lookup('template','secrets/' + 'ldap-secret.yml.j2') }}"
    - "{{ lookup('template','secrets/' + 'ldap-ca-config-map.yml.j2') }}"
  no_log: true
  when: oauth.ldap_enabled

- name: Create Custom Ingress Certificate Workloads
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    force: yes
    definition: "{{ item }}"
  loop:
  - "{{ lookup('template', 'secrets/ingress-certs.yml.j2') }}"
  - "{{ lookup('template', 'secrets/api-certs.yml.j2') }}"
  no_log: true
  when: custom_certs_enabled

- name: Create ACS Namespace 
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    definition: 
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        annotations:
          openshift.io/node-selector: ''
        labels:
          openshift.io/cluster-monitoring: 'true'
        name: stackrox
  when: acs_enabled

- name: Create Secret for ACS 
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    force: yes
    definition: "{{ lookup('template','secrets/' + 'acs-init-bundle.yml.j2') }}"
  when: acs_enabled

- name: Create ADP Namespace 
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    definition: 
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        annotations:
          openshift.io/node-selector: ''
        labels:
          openshift.io/cluster-monitoring: 'true'
        name: open-cluster-management-backup
  when: oadp_enabled

- name: Set Ingress Hostname Fact
  set_fact:
    adp_aws_access: |
      [default]
      aws_access_key_id = {{ ocp_install_aws_access_key }}
      aws_secret_access_key = {{ ocp_install_aws_secret_key }}
  when: oadp_enabled

- name: Disable Server Version CR
  k8s: 
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    force: yes
    definition: "{{ lookup('template','public-info-cluster-role.yml.j2') }}"

- name: Get AAP Password
  k8s_info:
    api_key: "{{ k8s_auth_api_key }}"
    host: "{{ k8s_auth_host }}"
    name: "{{ cluster_name }}-admin-password"
    api_version: v1
    kind: Secret
    namespace: ansible-automation-platform
  register: admin_password
  when: aap_enabled

- name: Apply TSSC App for MGMT
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    definition: "{{ lookup('template', 'argo/tssc-cluster-resources.yml.j2') }}"
  when: tssc_enabled