---
- name: Remove kubeadmin
  kubernetes.core.k8s:
    api_key: "{{ k8s_auth_api_key }}"
    host: "{{ k8s_auth_host }}"
    state: absent
    kind: Secret
    name: kubeadmin
    namespace: kube-system
