---
- name: Get OpenShift Infra Cluster Facts
  k8s_info:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    kind: Infrastructure
    name: cluster
  register: infra_facts

- name: Set Infra ID
  set_fact:
    infra_id: "{{ infra_facts.resources[0].status.infrastructureName }}"

- name: Create MachineAutoscaler
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    definition: "{{ lookup('template', 'machineautoscaler.yml.j2') }}"
  loop: "{{ lookup('dict', machineset_types) }}"