---
- name: Apply Cluster Resources Restore 
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    definition: "{{ lookup('template', 'oadp/'+item) }}"
  loop:
  - cluster-resources-restore.yml.j2

- name: Apply Namespaces Resources Restore 
  k8s:
    api_key: "{{ k8s_auth_api_key  }}"
    host: "{{ k8s_auth_host }}"
    state: present
    definition: "{{ lookup('template', 'oadp/'+item) }}"
  loop:
  - namespaces-resources-restore.yml.j2


