---
- name: Create Namespace
  k8s:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    state: present
    definition: "{{ lookup('template', 'argo/'+item) }}"
  loop:
  - gitops-ns.yml.j2

- name: Install GitOps Operator 
  k8s:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    state: present
    definition: "{{ lookup('template', 'argo/'+item) }}"
  loop:
  - gitops-sub.yml.j2
- name: Install ACM Operators
  k8s:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    state: present
    definition: "{{ lookup('template', 'restore-additional-blank-templates/'+item) }}"
  loop: 
  - acm-ns.yml.j2
  - acm-og.yml.j2
  - acm-sub.yml.j2

- name: Check if MCH CRD exists...
  k8s_info:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "multiclusterhubs.operator.open-cluster-management.io"
  register: mch_status_out
  until:
  - mch_status_out is defined
  - mch_status_out.resources is defined
  - mch_status_out.resources[0] is defined
  - mch_status_out.resources[0].status is defined
  - mch_status_out.resources[0].status.conditions is defined
  retries: 60
  delay: 10

- name: Install MCH
  k8s:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    state: present
    definition: "{{ lookup('template', 'restore-additional-blank-templates/'+item) }}"
  loop:
  - acm-mch.yml.j2

- name: Waiting for DataApp CustomResourceDefinition to be defined...
  k8s_info:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: dataprotectionapplications.oadp.openshift.io
  register: dataprotectionapp_status_out
  until:
  - dataprotectionapp_status_out is defined
  - dataprotectionapp_status_out.resources is defined
  - dataprotectionapp_status_out.resources[0] is defined
  - dataprotectionapp_status_out.resources[0].status is defined
  - dataprotectionapp_status_out.resources[0].status.conditions is defined
  retries: 60
  delay: 10

- name: Set ADP Secret Fact
  set_fact:
    adp_aws_access: |
      [default]
      aws_access_key_id = {{ ocp_install_aws_access_key }}
      aws_secret_access_key = {{ ocp_install_aws_secret_key }}

- name: Add ADP Secret
  k8s:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    state: present
    definition: "{{ lookup('template','secrets/' + 'adp-cloud-credentials.yml.j2') }}"

- name: Install DataProtectionApp
  k8s:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    state: present
    definition: "{{ lookup('template', 'oadp/'+item) }}"
  loop: 
  - adp-dpa.yml.j2

- name: Wait for backups to populate completely
  wait_for:
    timeout: 300
  delegate_to: localhost

- name: Check if Namespaces Backup exists...
  k8s_info:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    api_version: velero.io/v1
    kind: Backup
    name: "{{ resources_backup_name }}"
    namespace: "open-cluster-management-backup"
  register: check_backup
  until:
  - check_backup is defined
  - check_backup.resources is defined
  - check_backup.resources[0] is defined
  - check_backup.resources[0].status is defined
  when: resources_backup_name is defined

- name: Check if Cluster Resources Backup exists...
  k8s_info:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    api_version: velero.io/v1
    kind: Backup
    name: "{{ resources_backup_name }}"
    namespace: "open-cluster-management-backup"
  register: check_backup
  until:
  - check_backup is defined
  - check_backup.resources is defined
  - check_backup.resources[0] is defined
  - check_backup.resources[0].status is defined
  when: resources_backup_name is defined

- name: Apply Namespaces Resources Restore AAP
  k8s:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    state: present
    definition: "{{ lookup('template', 'oadp/'+item) }}"
  loop:
  - namespaces-resources-restore-gitops.yml.j2

- name: Waiting for Namespaces Resources Restore for Gitops to finish...
  k8s_info:
    api_key: "{{ K8S_AUTH_API_KEY  }}"
    host: "{{ K8S_AUTH_HOST }}"
    api_version: velero.io/v1
    kind: Restore
    namespace: "open-cluster-management-backup"
    name: "namespaces-resources-restore-gitops"
  register: namespace_restore_status_gitops
  until:
  - namespace_restore_status_gitops is defined
  - namespace_restore_status_gitops.resources is defined
  - namespace_restore_status_gitops.resources[0] is defined
  - namespace_restore_status_gitops.resources[0].status is defined
  - namespace_restore_status_gitops.resources[0].status.phase is defined
  - namespace_restore_status_gitops.resources[0].status.phase == "Completed" or namespace_restore_status_gitops.resources[0].status.phase == "PartiallyFailed"
  retries: 100 
  delay: 15