{{ if .Values.openshift_logging.enabled }}
# operator group yaml file elasticsearch operator
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat 
spec: {}
{{ end }}