kind: ConfigMap
apiVersion: v1
metadata:
  name: update-rs
  namespace: openshift-logging
data:
  updateRS.sh: >-
    #!/bin/bash
    oc patch elasticsearch/elasticsearch --type='json' -p='[{"op": "replace", "path": "/spec/managementState", "value":"Unmanaged"}]'
    for i in `oc get rs -l component=elasticsearch -o name`; 
    do 
    oc set env -c elasticsearch $i ES_JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true"; 
    oc scale $i --replicas=0; 
    done
    
