# Default values for rh-acs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
base_domain:
cluster_name:
acs:
  channel: rhacs-3.73
  installPlanApproval: Manual
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  namespace: stackrox