# Default values for file integrity operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fio:
  name: file-integrity-operator
  namespace: openshift-file-integrity
  installPlanApproval: Manual
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: