openshift_version: 4.12.20
vpc_id:
cluster_name: infra
base_domain: 
region: us-east-1

#LDAP vars
ldap_filter: 

#LDAP groupsync vars
group_filter: 
cluster_admin_group: 

machineset_types:
  infra:
    replicas:
      min: 1
      max: 2
  worker:
    replicas:
      min: 1
      max: 2
  storage:
    replicas:
      min: 1
      max: 2
