{{ if .Values.acm.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.acm.subName }}
  namespace: {{ .Values.acm.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.acm.channel }}
  sourceNamespace: {{ .Values.acm.sourceNamespace }}
  source: {{ .Values.acm.source }}
  installPlanApproval: {{ .Values.acm.installPlanApproval }}
  name: {{ .Values.acm.name }}
{{ end }}