{{ if .Values.acm_enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: acm-operatorgroup
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
{{ end }}