{{ if or (eq .Values.cluster_name "mgmt") (eq .Values.cluster_name "infra") }}
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  name: {{ .Values.cluster_set }}
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterSet: {{ .Values.cluster_set }}
{{ end }}