{{ if or (eq .Values.cluster_name "mgmt") (eq .Values.cluster_name "infra") }}
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  name: momot-clusters
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterSet: momot-clusters
{{ end }}