{{ if .Values.mgmt_cluster }}
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: "{{ .Values.organization }}-clusters"
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift
{{ end }}