{{ if .Values.acm_enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm-operator-subscription
  namespace: open-cluster-management
spec:
  channel: {{ .Values.acm_channel }}
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  installPlanApproval: Automatic
  name: advanced-cluster-management
{{ end }}