{{ if .Values.mgmt_cluster }}
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: momot-clusters
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift
{{ end }}