{{ if .Values.acm.enabled }}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.acm.namespace }}
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
{{ end }}