{{ if .Values.cost.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.cost.name }}
  namespace: {{ .Values.cost.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: {{ .Values.cost.channel }}
  installPlanApproval: {{ .Values.cost.installPlanApproval }}
  name: {{ .Values.cost.name }}
  source: {{ .Values.cost.source }}
  sourceNamespace: {{ .Values.cost.sourceNamespace }}
{{ if .Values.cost.channel }}
  channel: {{ .Values.cost.channel }}
{{ end }}
{{ end }}