{{ if .Values.cost.enabled }}
apiVersion: costmanagement-metrics-cfg.openshift.io/v1beta1
kind: CostManagementMetricsConfig
metadata:
  name: costmanagementmetricscfg-{{ .Values.cluster_name }}-v1beta1
  namespace: costmanagement-metrics-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  upload:
    ingress_path: /api/ingress/v1/upload
    upload_cycle: 360
    upload_toggle: true
    validate_cert: true
  volume_claim_template:
    spec:
      storageClassName: ocs-storagecluster-ceph-rbd
  packaging:
    max_reports_to_store: 30
    max_size_MB: 100
  api_url: 'https://cloud.redhat.com'
  prometheus_config:
    collect_previous_data: true
    context_timeout: 120
    disable_metrics_collection_cost_management: false
    disable_metrics_collection_resource_optimization: false
    service_address: 'https://thanos-querier.openshift-monitoring.svc:9091'
    skip_tls_verification: false
  authentication:
    type: token
  source:
    check_cycle: 1440
    create_source: true
    sources_path: /api/sources/v1.0/
    name: {{ .Values.cluster_name }}-{{ .Values.organization }}-cluster
{{ end }}