{{ .Values.aap.enabled  }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.aap.name }}
  namespace: {{ .Values.aap.namespace }}
spec:
  targetNamespaces:
    - {{ .Values.aap.namespace }}
{{ end }}