{{ if or (eq .Values.cluster_name "mgmt") (eq .Values.cluster_name "infra") }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ansible-automation-platform
  namespace: ansible-automation-platform
spec:
  targetNamespaces:
    - ansible-automation-platform
{{ end }}