{{ if or (eq .Values.cluster_name "mgmt") (eq .Values.cluster_name "infra") }}
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: ansible-automation-platform
  annotations:
    openshift.io/node-selector: ''
  labels:
    openshift.io/cluster-monitoring: 'true'
{{ end }}