{{ .Values.aap_enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: ansible-automation-platform
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
{{ end }}