{{ .Values.aap.enabled  }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.aap.name }}
  namespace: {{ .Values.aap.namespace }}
spec:
  installPlanApproval: {{ .Values.aap.installPlanApproval }}
  name: {{ .Values.aap.name }}
  source: {{ .Values.aap.source }}
  sourceNamespace: {{ .Values.aap.sourceNamespace }}
{{ if .Values.aap.channel }}
  channel: {{ .Values.aap.channel }}
{{ end }}
