{{ .Values.aap.enabled  }}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.aap.namespace }}
  annotations:
    openshift.io/node-selector: ''
  labels:
    openshift.io/cluster-monitoring: 'true'
{{ end }}