---
- name: Waiting for ScanSetting CustomResourceDefinition to be defined...
  k8s_info:
    api_key: "{{ K8S_AUTH_API_KEY }}"
    host: "{{ K8S_AUTH_HOST }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: scansettings.compliance.openshift.io
  register: scansetting_status_out
  until:
  - scansetting_status_out is defined
  - scansetting_status_out.resources is defined
  - scansetting_status_out.resources[0] is defined
  retries: 30
  delay: 10

- name: Waiting for ScanSettingBinding CustomResourceDefinition to be defined...
  k8s_info:
    api_key: "{{ K8S_AUTH_API_KEY }}"
    host: "{{ K8S_AUTH_HOST }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: scansettingbindings.compliance.openshift.io
  register: scansettingbinding_status_out
  until:
  - scansettingbinding_status_out is defined
  - scansettingbinding_status_out.resources is defined
  - scansettingbinding_status_out.resources[0] is defined
  retries: 30
  delay: 10

- name: Get Compliance Scans
  k8s_info:
    api_key: "{{ K8S_AUTH_API_KEY }}"
    host: "{{ K8S_AUTH_HOST }}"
    api_version: compliance.openshift.io/v1alpha1
    kind: ComplianceScan
    namespace: openshift-compliance
  no_log: true
  register: compliance_scans_out

- name: Check Compliance Scans
  k8s_info:
    api_key: "{{ K8S_AUTH_API_KEY }}"
    host: "{{ K8S_AUTH_HOST }}"
    api_version: compliance.openshift.io/v1alpha1
    kind: ComplianceScan
    name: "{{ item.metadata.name }}"
    namespace: openshift-compliance
  register: compliance_scan_result
  no_log: true
  loop: "{{ compliance_scans_out.resources }}"
  until: 
  - compliance_scan_result.resources[0].status.phase == "DONE"
  retries: 30
  delay: 10

- name: Pause Machine Configs
  k8s:
    api_key: "{{ K8S_AUTH_API_KEY }}"
    host: "{{ K8S_AUTH_HOST }}"
    state: present
    definition:
      api_version: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: "{{ item }}"
      spec:
        paused: true
  loop:
  - master
  - infra
  - worker
  when: remediation_list is defined and (remediation_list|length > 0)

- name: Get PodDisruptionBudgets
  k8s_info:
    api_version: policy/v1beta1
    kind: PodDisruptionBudget
    namespace: openshift-storage
  register: poddisruptionbudgets

- name: Modify PodDisruptionBudget to allow storage nodes to drain
  k8s:
    state: present
    definition:
      apiVersion: policy/v1beta1
      kind: PodDisruptionBudget
      metadata:
        namespace: openshift-storage 
        name: "{{ item.metadata.name }}"
      spec:
        maxUnavailable: 1
  loop: "{{ poddisruptionbudgets.resources | flatten }}"
  when: item.spec.minAvailable is not defined

- name: Harden OpenShift Cluster with Compliance Operator
  include_tasks: harden_ocp.yml
  loop: "{{ remediation_list }}"
  when: remediation_list is defined and (remediation_list|length > 0)
  
- name: Resume Machine Configs
  k8s:
    api_key: "{{ K8S_AUTH_API_KEY }}"
    host: "{{ K8S_AUTH_HOST }}"
    state: present
    definition:
      api_version: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: "{{ item }}"
      spec:
        paused: false
  loop:
  - master
  - infra
  - worker
  when: remediation_list is defined and (remediation_list|length > 0)