# yaml file to create namespace for Group Sync Operator
{{ if .Values.gso.enabled }}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.gso.namespace }}
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
{{ end }}
