{{ if .Values.oauth.groupsync_enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: group-sync-operator
  namespace: group-sync-operator
spec:
  targetNamespaces:
    - group-sync-operator
{{ end }}