# yaml file to create namespace for Group Sync Operator
{{ if .Values.oauth.groupsync_enabled }}
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: group-sync-operator
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
{{ end }}
