{{ if .Values.gso.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.gso.namespace }}
  namespace: {{ .Values.gso.namespace }}
spec:
  targetNamespaces:
    - {{ .Values.gso.namespace }}
{{ end }}