{{ if .Values.gso.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.gso.name }}
  namespace: {{ .Values.gso.namespace }}
spec:
  installPlanApproval: {{ .Values.gso.installPlanApproval }}
  name: {{ .Values.gso.name }}
  source: {{ .Values.gso.source }}
  sourceNamespace: {{ .Values.gso.sourceNamespace }}
{{ if .Values.gso.channel }}
  channel: {{ .Values.gso.channel }}
{{ end }}