{{ if .Values.gatekeeper.enabled }}
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: openshift-gatekeeper-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  match:
    - excludedNamespaces:
        - ansible-automation-platform
        - hive
        - kube-*
        - local-quay
        - multicluster-engine
        - open-cluster-management
        - open-cluster-management-*
        - openshift-*
        - rhacs-operator
        - stackrox
      processes: ["*"]
{{ end }}
