{{ if .Values.gatekeeper_operator }}
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: openshift-gatekeeper-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  match:
    - excludedNamespaces: ["kube-system", "openshift-gatekeeper-system", "openshift-logging"]
      processes: ["*"]
{{ end }}
