{{ if .Values.gatekeeper.enabled }}
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  validatingWebhook: Enabled
  webhook:
    logLevel: INFO
    replicas: 2
  image:
    image: >-
      registry.redhat.io/rhacm2/gatekeeper-rhel8:{{ .Values.gatekeeper.gk_img_tag }}
  audit:
    logLevel: INFO
    replicas: 1
{{ end }}