{{ if .Values.gatekeeper.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/gatekeeper-operator-product.openshift-operators: ''
  name: {{ .Values.gatekeeper.name }}
  namespace: {{ .Values.gatekeeper.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: {{ .Values.gatekeeper.channel }}
  installPlanApproval: {{ .Values.gatekeeper.installPlanApproval }}
  name: {{ .Values.gatekeeper.name }}
  source: {{ .Values.gatekeeper.source }}
  sourceNamespace: {{ .Values.gatekeeper.sourceNamespace }}
{{ end }}
