{{ if .Values.amq_broker.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.amq_broker.name }}
  namespace: {{ .Values.amq_broker.namespace }}
spec:
  channel: {{ .Values.amq_broker.channel }}
  installPlanApproval: {{ .Values.amq_broker.installPlanApproval }}
  name: {{ .Values.amq_broker.name }}
  source: {{ .Values.amq_broker.source }}
  sourceNamespace: {{ .Values.amq_broker.sourceNamespace }}
{{ end }}