{{ if .Values.fio.enabled }}
{{ if .Capabilities.APIVersions.Has "fileintegrity.openshift.io/v1alpha1" -}}
apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  name: worker-fileintegrity
  namespace: {{ .Values.fio.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  nodeSelector:
      node-role.kubernetes.io/worker: ""
  config: {}
{{- end }}
{{ end }}
