{{ if .Values.fio.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.fio.name }}
  namespace: {{ .Values.fio.namespace }}
spec:
  targetNamespaces:
  - {{ .Values.fio.namespace }}
{{ end }}