#clusterautoscaler vars
pod_priority_threshold: -10
resource_limits:
  max_nodes_total: 22
  cores:
    min: 72
    max: 344
  memory:
    min: 288
    max: 1376
scaledown:
  enabled: true
  delay_after_add: 10m
  delay_after_delete: 5m
  delay_after_failure: 30s
  unneeded_time: 60s
