{{ if .Values.oadp_enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: redhat-oadp-operator-group
  namespace: open-cluster-management-backup
spec:
  targetNamespaces:
  - open-cluster-management-backup
{{ end }}