{{ if .Values.adp.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: redhat-oadp-operator-group
  namespace: {{ .Values.adp.namespace }}
spec:
  targetNamespaces:
  - {{ .Values.adp.namespace }}
{{ end }}