{{ if .Values.adp.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.adp.namespace }}
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
{{ end }}