{{ if .Values.adp.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.adp.nameSub }}
  namespace: {{ .Values.adp.namespace }}
spec:
  channel: {{ .Values.adp.channel }}
  installPlanApproval: {{ .Values.adp.installPlanApproval }}
  name: {{ .Values.adp.name }}
  source: {{ .Values.adp.source }}
  sourceNamespace: {{ .Values.adp.sourceNamespace }}
{{ end }}