{{ if .Values.oadp_enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management-backup
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
{{ end }}