apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: open-cluster-management-backup
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"