{{ if .Values.oadp_enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: resources-schedule
  namespace: open-cluster-management-backup
  labels:
    app.kubernetes.io/instance: rh-adp
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  schedule: 0 */1 * * *
  template:
    defaultVolumesToRestic: true
    hooks: {}
    includeClusterResources: true
    excludedNamespaces:
      - default
      - kube-node-lease
      - kube-public
      - kube-system
      - multicluster-engine
      - open-cluster-management
      - open-cluster-management-agent
      - open-cluster-management-agent-addon
      - open-cluster-management-backup
      - open-cluster-management-hub
      - openshift
      - openshift-apiserver
      - openshift-apiserver-operator
      - openshift-authentication
      - openshift-authentication-operator
      - openshift-cloud-controller-manager
      - openshift-cloud-controller-manager-operator
      - openshift-cloud-credential-operator
      - openshift-cluster-csi-drivers
      - openshift-cluster-machine-approver
      - openshift-cluster-node-tuning-operator
      - openshift-cluster-samples-operator
      - openshift-cluster-storage-operator
      - openshift-cluster-version
      - openshift-compliance
      - openshift-config
      - openshift-config-managed
      - openshift-config-operator
      - openshift-console
      - openshift-console-operator
      - openshift-console-user-settings
      - openshift-controller-manager
      - openshift-controller-manager-operator
      - openshift-dns
      - openshift-dns-operator
      - openshift-etcd
      - openshift-etcd-operator
      - openshift-file-integrity
      - openshift-gatekeeper-system
      - openshift-host-network
      - openshift-image-registry
      - openshift-infra
      - openshift-ingress
      - openshift-ingress-canary
      - openshift-ingress-operator
      - openshift-insights
      - openshift-kni-infra
      - openshift-kube-apiserver
      - openshift-kube-apiserver-operator
      - openshift-kube-controller-manager
      - openshift-kube-controller-manager-operator
      - openshift-kube-scheduler
      - openshift-kube-scheduler-operator
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator
      - openshift-kubevirt-infra
      - openshift-logging
      - openshift-machine-api
      - openshift-machine-config-operator
      - openshift-marketplace
      - openshift-monitoring
      - openshift-multus
      - openshift-network-diagnostics
      - openshift-network-operator
      - openshift-node
      - openshift-oauth-apiserver
      - openshift-openstack-infra
      - openshift-operator-lifecycle-manager
      - openshift-operators
      - openshift-operators-redhat
      - openshift-ovirt-infra
      - openshift-sdn
      - openshift-service-ca
      - openshift-service-ca-operator
      - openshift-storage
      - openshift-user-workload-monitoring
      - openshift-vsphere-infra
      - stackrox
      - newrelic
      - fluent-bit-logging
    includedResources:
      - pods
      - persistentvolumeclaims
      - persistentvolumes
      - clusterroles.rbac.authorization.k8s.io
      - clusterrolebindings.rbac.authorization.k8s.io
      - securitycontextconstraints.security.openshift.io
      - serviceaccounts
      - roles.rbac.authorization.k8s.io
      - rolebindings.rbac.authorization.k8s.io
      - secrets
      - configmaps
      - argocds.argoproj.io
      - deployments.apps
      - deploymentconfigs.apps.openshift.io
      - statefulsets.apps
      - daemonsets.apps
      - replicasets.apps
      - jobs.batch
      - cronjobs.batch
      - replicationcontrollers
      - horizontalpodautoscalers.autoscaling
      - services
      - routes.route.openshift.io
      - buildconfigs.build.openshift.io
      - builds.build.openshift.io
      - automationcontrollers.automationcontroller.ansible.com
      - appprojects.argoproj.io
      - application.argoproj.io
    storageLocation: dpa-{{ .Values.cluster_name }}-1
    ttl: 48h0m0s
    volumeSnapshotLocations:
      - dpa-{{ .Values.cluster_name }}-1
{{ end }}