apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: resources-schedule
  namespace: {{ .Values.adp.namespace }}
  labels:
    app.kubernetes.io/instance: rh-adp
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  schedule: 0 */1 * * *
  template:
    defaultVolumesToRestic: false
    hooks: {}
    includeClusterResources: true
    excludedNamespaces:
      - default
      - kube-node-lease
      - kube-public
      - kube-system
      - multicluster-engine
      - open-cluster-management
      - open-cluster-management-agent
      - open-cluster-management-agent-addon
      - {{ .Values.adp.namespace }}
      - open-cluster-management-hub
      - openshift
      - openshift-apiserver
      - openshift-apiserver-operator
      - openshift-authentication
      - openshift-authentication-operator
      - openshift-cloud-controller-manager
      - openshift-cloud-controller-manager-operator
      - openshift-cloud-credential-operator
      - openshift-cluster-csi-drivers
      - openshift-cluster-machine-approver
      - openshift-cluster-node-tuning-operator
      - openshift-cluster-samples-operator
      - openshift-cluster-storage-operator
      - openshift-cluster-version
      - openshift-compliance
      - openshift-config
      - openshift-config-managed
      - openshift-config-operator
      - openshift-console
      - openshift-console-operator
      - openshift-console-user-settings
      - openshift-controller-manager
      - openshift-controller-manager-operator
      - openshift-dns
      - openshift-dns-operator
      - openshift-etcd
      - openshift-etcd-operator
      - openshift-file-integrity
      - openshift-gatekeeper-system
      - openshift-host-network
      - openshift-image-registry
      - openshift-infra
      - openshift-ingress
      - openshift-ingress-canary
      - openshift-ingress-operator
      - openshift-insights
      - openshift-kni-infra
      - openshift-kube-apiserver
      - openshift-kube-apiserver-operator
      - openshift-kube-controller-manager
      - openshift-kube-controller-manager-operator
      - openshift-kube-scheduler
      - openshift-kube-scheduler-operator
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator
      - openshift-kubevirt-infra
      - openshift-logging
      - openshift-machine-api
      - openshift-machine-config-operator
      - openshift-marketplace
      - openshift-monitoring
      - openshift-multus
      - openshift-network-diagnostics
      - openshift-network-operator
      - openshift-node
      - openshift-oauth-apiserver
      - openshift-openstack-infra
      - openshift-operator-lifecycle-manager
      - openshift-operators
      - openshift-operators-redhat
      - openshift-ovirt-infra
      - openshift-sdn
      - openshift-service-ca
      - openshift-service-ca-operator
      - openshift-storage
      - openshift-user-workload-monitoring
      - openshift-vsphere-infra
      - stackrox
      - newrelic
      - fluent-bit-logging
    storageLocation: {{ .Values.cluster_name }}-1
    ttl: 48h0m0s
