{{ if .Values.code_ready_workspace_enabled }}
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-workspaces
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
{{ end }}