{{ if .Values.code_ready_workspace_enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: codeready-workspaces
  namespace: openshift-workspaces
spec:
  channel: latest
  installPlanApproval: AutomaticW
  name: codeready-workspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{ end }}